milestone_output_path <- "milestones"
milestone_delim <- "^#.*ms[ 0-9]*[ -]+"
milestone_delim_text <- "\\(MILESTONE "
milestone_delim_quarto <- "## Milestone "
slide_output_path <- "slides"
course_name_computer <- "shiny intro_"
course_name_human <- "Introductory Shiny"
author <- "Brendan Clarke"
logo <- "..//src//images//KLN_banner_v05_125.png"
css_path <- "..//src//images//logo.css"
outline_input_path <- "src//session_outlines"
text_input_path <- "src//text_sections"
